### ISSUE TITLE
incompatible upstream: vscode-json-languageservice 3.10.0

### ISSUE THREAD

**Issue by bollwyvl** [redhat-developer/yaml-language-server#345]
## Describe the bug

`vscode-json-languageservice@3.10.0` [dropped](https://github.com/microsoft/vscode-json-languageservice/compare/v3.9.1...v3.10.0#diff-6a390b0906c50b9f2003de429ebea4feb90bf60318f102a21a5e7db84115db6e) a few hours ago, and has removed `src/services/jsonDefinition.ts`.

Thanks for maintaining this, hope this can help save some pain!

## Expected Behavior

Should run normally.

## Current Behavior

Does not run.

## Steps to Reproduce

1. `$> npm install yaml-language-server`
2. 
```bash
$> node ./node_modules/.bin/yaml-language-server || echo "💥"

internal/modules/cjs/loader.js:955
  throw err;
  ^

Error: Cannot find module 'vscode-json-languageservice/lib/umd/services/jsonDefinition'
Require stack:
- ~/node_modules/yaml-language-server/out/server/src/languageservice/services/yamlDefinition.js
- ~/node_modules/yaml-language-server/out/server/src/languageservice/yamlLanguageService.js
- ~/node_modules/yaml-language-server/out/server/src/server.js
- ~/node_modules/yaml-language-server/bin/yaml-language-server
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (~/node_modules/yaml-language-server/out/server/src/languageservice/services/yamlDefinition.js:5:26)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '~/node_modules/yaml-language-server/out/server/src/languageservice/services/yamlDefinition.js',
    '~/node_modules/yaml-language-server/out/server/src/languageservice/yamlLanguageService.js',
    '~/node_modules/yaml-language-server/out/server/src/server.js',
    '~/node_modules/yaml-language-server/bin/yaml-language-server'
  ]
}
💥
```

## Environment
- [x] Windows
- [x] Mac
- [x] Linux

**Comment by adrianlzt** [comment]
Workaround while using this with nvim:
```
cd $HOME/.config/coc/extensions/node_modules/coc-yaml/node_modules/yaml-language-server
npm install vscode-json-languageservice@3.9.1
```

**Comment by JPinkney** [comment]
This is only when you use npm right?

If I do:
```
yarn
yarn run compile
```
everything is done successfully

**Comment by JPinkney** [comment]
I've merged the PR to make it compatible
