### ISSUE TITLE
Youcomplete manual config

### ISSUE THREAD

**Issue by goodwillhacking** [redhat-developer/yaml-language-server#355]
## Summary
I would like kubernetes to be my default yaml schema. Forgive the lazy question but how would I go about passing the equivalent of the below schema definition via CMD:
```
yaml.schemas: {
    "https://json.schemastore.org/composer": "/*",
    "kubernetes": "*.yaml"
}
```
## Relevant information
My vim LSP settings for you-complete-me.
```
   let g:ycm_language_server = [
\{  'name': 'yaml',
\   'filetypes': [ 'yaml'],
\   'cmdline': [ 'node', expand( '$NODE_BIN/yaml-language-server' ), '--stdio' ],
 \}]
```

**Comment by JPinkney** [comment]
I'm not really familiar with YCM but I think you'd have to follow: https://github.com/ycm-core/YouCompleteMe#lsp-configuration and it should be something like:

```
def Settings( **kwargs ):
  if kwargs[ 'language' ] == 'yaml':
    return {
     'yaml.schemas': {
        "https://json.schemastore.org/composer": "/*",
        "kubernetes": "*.yaml"
     }
    }
```

there isn't any way to pass the schema via command line

**Comment by goodwillhacking** [comment]
@JPinkney thank you. I appreciate it. Your config suggestion appears to be correct. I just dont think YCM and YLS play nice together at the moment. Got the following error below which is YCM related. Will try hunt down a solution there. Closing this for now - Cheers

```
No support for ExecuteCommand command in server for yaml
INFO - No support for FixIt command in server for yaml
INFO - Found definitionProvider support for command GoToDefinition in yaml
INFO - Found definitionProvider support for command GoToDeclaration in yaml
INFO - Found definitionProvider support for command GoTo in yaml
INFO - No support for GoToType command in server for yaml
INFO - No support for GoToImplementation command in server for yaml
INFO - No support for GoToReferences command in server for yaml
INFO - No support for RefactorRename command in server for yaml
INFO - No support for Format command in server for yaml
INFO - No support for GoToSymbol command in server for yaml
INFO - Always supporting StopServer for yaml
 INFO - Always supporting RestartServer for yaml
INFO - Always supporting GetHover for yaml
Traceback (most recent call last):
   File "/home/nico/.vim/bundle/youcompleteme/third_party/ycmd/third_party/bottle/bottle.py", line 868, in _handle
      return route.call(**args)
   File "/home/nico/.vim/bundle/youcompleteme/third_party/ycmd/third_party/bottle/bottle.py", line 1748, in wrapper
      rv = callback(*a, **ka)
    File "/home/nico/.vim/bundle/youcompleteme/third_party/ycmd/ycmd/watchdog_plugin.py", line 97, in wrapper
      return callback( *args, **kwargs )
    File "/home/nico/.vim/bundle/youcompleteme/third_party/ycmd/ycmd/hmac_plugin.py", line 62, in wrapper
      body = callback( *args, **kwargs )
    File "/home/nico/.vim/bundle/youcompleteme/third_party/ycmd/ycmd/handlers.py", line 94, in RunCompleterCommand
      return _JsonResponse( completer.OnUserCommand(
    File "/home/nico/.vim/bundle/youcompleteme/third_party/ycmd/ycmd/completers/completer.py", line 463, in OnUserCommand
      raise ValueError( self.UserCommandsHelpMessage() )
  ValueError: Supported commands are:
  GetHover
  GoTo
  GoToDeclaration
  GoToDefinition
```

**Comment by guilhermehubner** [comment]
@goodwillhacking did you find something? I am trying to make it work, no success so far
