### ISSUE TITLE
Server is sending client/registerCapability even if the client doesn't support dynamic capability registration

### ISSUE THREAD

**Issue by hugopl** [redhat-developer/yaml-language-server#377]
## Server is sending `client/registerCapability` even if the client doesn't support dynamic capability registration.

Here's a dump of the JSON RPC communication, using yaml-language-server version 0.13.0 on [Tijolo](https://github.com/hugopl/tijolo) editor from git.

```
LSP.Yaml: Starting LSP for "yaml-language-server --stdio" on pid 9566

LSP.Yaml: ==> {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":9552,"rootPath":"/home/hugo/src/tijolo","rootUri":"file:///home/hugo/src/tijolo","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true},"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":false},"workspaceFolders":true},"textDocument":{"synchronization":{"dynamicRegistration":false,"willSave":true,"willSaveWaitUntil":false,"didSave":true},"definition":{"dynamicRegistration":false},"documentHighlight":{"dynamicRegistration":false},"documentSymbol":{"dynamicRegistration":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":false}}},"trace":"off","workspaceFolders":[{"uri":"file:///home/hugo/src/tijolo","name":"project"}]}}

LSP.Yaml: <== {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":1,"completionProvider":{"resolveProvider":false},"hoverProvider":true,"documentSymbolProvider":true,"documentFormattingProvider":false,"documentRangeFormattingProvider":false,"documentLinkProvider":{},"workspace":{"workspaceFolders":{"changeNotifications":true,"supported":true}}}}}

LSP.Yaml: ==> {"method":"initialized","params":{},"jsonrpc":"2.0"}

LSP.Yaml: <== {"jsonrpc":"2.0","id":0,"method":"client/registerCapability","params":{"registrations":[{"id":"d9f128c6-616e-40bd-a944-9d463f0c846b","method":"workspace/didChangeWorkspaceFolders","registerOptions":{}}]}}

LSP.Yaml: ==> {"jsonrpc":"2.0","id":0,"error":{"code":-32601,"message":"Unhandled method client/registerCapability"}}

LSP.Yaml: <== {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Registering request handler for workspace/didChangeWorkspaceFolders failed."}}

LSP.Yaml: <== {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"(node:9566) UnhandledPromiseRejectionWarning: Error: Unhandled method client/registerCapability\n    at handleResponse (/usr/lib/node_modules/yaml-language-server/node_modules/vscode-jsonrpc/lib/main.js:436:48)\n    at processMessageQueue (/usr/lib/node_modules/yaml-language-server/node_modules/vscode-jsonrpc/lib/main.js:263:17)\n    at Immediate.<anonymous> (/usr/lib/node_modules/yaml-language-server/node_modules/vscode-jsonrpc/lib/main.js:247:13)\n    at processImmediate (internal/timers.js:461:21)"}}

LSP.Yaml: <== {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"(node:9566) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)"}}

LSP.Yaml: <== {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"(node:9566) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."}}
```

## Expected Behavior
This request:
```
{"jsonrpc":"2.0","id":0,"method":"client/registerCapability","params":{"registrations":[{"id":"d9f128c6-616e-40bd-a944-9d463f0c846b","method":"workspace/didChangeWorkspaceFolders","registerOptions":{}}]}}
```
should not be sent, since the client doesn't support dynamic capability registration and inform this to the server.

## Current Behavior
A `client/registerCapability` is sent.

## Steps to Reproduce
1. Try to use it on a client that doesn't support dynamic capability registration.

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)

**Comment by JPinkney** [comment]
Can you try with our 0.14.0 release? I believe this should be fixed

**Comment by hugopl** [comment]
I'm going to wait some days for the [AUR package](https://aur.archlinux.org/packages/yaml-language-server/) update and test it.

**Comment by hugopl** [comment]
Just tested it, working nicely, thanks! :tada:
