### ISSUE TITLE
Cannot create property 'parent' on string '' when using empty YAML tags

### ISSUE THREAD

**Issue by medihack** [redhat-developer/yaml-language-server#537]
## Describe the bug

When entering a YAML tag without value (e.g. `foo: !!str`) into an editor that is using `yaml-language-server`, the worker throws the error `Cannot create property 'parent' on string ''`. One can easily replicate this with `VSCode` or `monaco-yaml` (full stack trace below).

## Expected Behavior

Should handle a YAML tag without value without throwing an error on the console.

## Current Behavior

Throws an error on the console.

## Steps to Reproduce
1. Go to https://monaco-yaml.js.org/
2. Open the developer console
3. Enter `foo: !!str` somewhere in the online editor
4. Watch the console

## Environment
- [x] Windows
- [] Mac (but I guess here, too)
- [x] Linux
- [ ] other (please specify)

## Trace

```
// from VSCode output panel
[Error - 5:28:07 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot create property 'parent' on string ''
  Code: -32603 
[Error - 5:28:07 PM] (node:705) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'parent' on string ''
    at storeMappingPair (/home/kai/.vscode-server/extensions/redhat.vscode-yaml-0.22.0/node_modules/yaml-language-server-parser/dist/src/loader.js:287:26)
    at readBlockMapping (/home/kai/.vscode-server/extensions/redhat.vscode-yaml-0.22.0/node_modules/yaml-language-server-parser/dist/src/loader.js:958:17)
    at composeNode (/home/kai/.vscode-server/extensions/redhat.vscode-yaml-0.22.0/node_modules/yaml-language-server-parser/dist/src/loader.js:1164:21)
    at readDocument (/home/kai/.vscode-server/extensions/redhat.vscode-yaml-0.22.0/node_modules/yaml-language-server-parser/dist/src/loader.js:1307:5)
    at loadDocuments (/home/kai/.vscode-server/extensions/redhat.vscode-yaml-0.22.0/node_modules/yaml-language-server-parser/dist/src/loader.js:1349:9)
    at Object.loadAll (/home/kai/.vscode-server/extensions/redhat.vscode-yaml-0.22.0/node_modules/yaml-language-server-parser/dist/src/loader.js:1373:21)
    at Object.parse (/home/kai/.vscode-server/extensions/redhat.vscode-yaml-0.22.0/node_modules/yaml-language-server/out/server/src/languageservice/parser/yamlParser07.js:82:10)
    at YamlDocuments.ensureCache (/home/kai/.vscode-server/extensions/redhat.vscode-yaml-0.22.0/node_modules/yaml-language-server/out/server/src/languageservice/parser/yaml-documents.js:44:40)
    at YamlDocuments.getYamlDocument (/home/kai/.vscode-server/extensions/redhat.vscode-yaml-0.22.0/node_modules/yaml-language-server/out/server/src/languageservice/parser/yaml-documents.js:23:14)
    at YAMLValidation.<anonymous> (/home/kai/.vscode-server/extensions/redhat.vscode-yaml-0.22.0/node_modules/yaml-language-server/out/server/src/languageservice/services/yamlValidation.js:56:70)
(Use `node --trace-warnings ...` to show where the warning was created)
[Error - 5:28:07 PM] (node:705) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[Error - 5:28:07 PM] (node:705) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 5:28:07 PM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed with message: Cannot create property 'parent' on string ''
  Code: -32603 
[Error - 5:28:08 PM] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Cannot create property 'parent' on string ''
  Code: -32603 
```

**Comment by gorkem** [comment]
I can not reproduce this anymore. Assuming it is fixed now. Please reopen if you still can observe it
