### ISSUE TITLE
TypeError: i.startsWith is not a function

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/yaml-language-server#747]
## Describe the bug
Telemetry data shows a high number (>50% of all errors) of "TypeError: i.startsWith is not a function" errors on `textDocument/hover` and completion requests apparently

## Expected Behavior
No error

## Current Behavior
Errors are thrown:
```
TypeError: i.startsWith is not a function
    at /Users/_username_/.vscode/extensions/redhat.vscode-yaml-1.8.0/dist/languageserver.js:2:533672
    at T (/Users/_username_/.vscode/extensions/redhat.vscode-yaml-1.8.0/dist/languageserver.js:2:534665)
    at /Users/_username_/.vscode/extensions/redhat.vscode-yaml-1.8.0/dist/languageserver.js:2:523312
    at T (/Users/_username_/.vscode/extensions/redhat.vscode-yaml-1.8.0/dist/languageserver.js:2:525873)
    at f.getMatchingSchemas (/Users/_username_/.vscode/extensions/redhat.vscode-yaml-1.8.0/dist/languageserver.js:2:521654)
    at t.YamlCompletion.addPropertyCompletions (/Users/_username_/.vscode/extensions/redhat.vscode-yaml-1.8.0/dist/languageserver.js:2:560153)
    at t.YamlCompletion.&lt;anonymous&gt; (/Users/_username_/.vscode/extensions/redhat.vscode-yaml-1.8.0/dist/languageserver.js:2:558169)
    at Generator.next (&lt;anonymous&gt;)
    at s (/Users/_username_/.vscode/extensions/redhat.vscode-yaml-1.8.0/dist/languageserver.js:2:550676)
```

## Steps to Reproduce
No idea

**Comment by fbricon** [comment]
This error started appearing with vscode-yaml 1.8.0

**Comment by msivasubramaniaan** [comment]
This issue was resolved as part of the below ticket
https://github.com/redhat-developer/vscode-yaml/issues/790
