### ISSUE TITLE
Incorrect yaml.customTags description in README.md

### ISSUE THREAD

**Issue by semidefinite** [redhat-developer/yaml-language-server#76]
README.md states (also vscode-yaml's README.md):

The following settings are supported:
* `yaml.customTags`: Array of custom tags that the parser will validate against. It has two ways to be used. Either an item in the array is a custom tag such as "!Ref" or you can specify the type of the object !Ref should be by doing "!Ref Scalar". For example: ["!Ref", "!Some-Tag Scalar"]. The type of object can be one of Scalar, Sequence, Mapping, Map.

However if I add the following to .vscode\settings.json:
```
{
  "yaml.customTags": [
      "!Ref Scalar"
      ]
}
```
The Yaml Support server crashes:
```
c:\Users\semidefinite\.vscode\extensions\redhat.vscode-yaml-0.0.13\node_modules\yaml-language-server\out\server\node_modules\js-yaml\lib\js-yaml\type.js:57
    throw new YAMLException('Unknown kind "' + this.kind + '" is specified for "' + tag + '" YAML type.');
    ^
YAMLException: Unknown kind "Scalar" is specified for "!Ref" YAML type.
    at new Type (c:\Users\semidefinite\.vscode\extensions\redhat.vscode-yaml-0.0.13\node_modules\yaml-language-server\out\server\node_modules\js-yaml\lib\js-yaml\type.js:57:11)
    at js_yaml_1.Schema.create.customTags.map (c:\Users\semidefinite\.vscode\extensions\redhat.vscode-yaml-0.0.13\node_modules\yaml-language-server\out\server\src\languageservice\parser\yamlParser.js:198:16)
    at Array.map (native)
    at Object.parse (c:\Users\semidefinite\.vscode\extensions\redhat.vscode-yaml-0.0.13\node_modules\yaml-language-server\out\server\src\languageservice\parser\yamlParser.js:196:71)
    at validateTextDocument (c:\Users\semidefinite\.vscode\extensions\redhat.vscode-yaml-0.0.13\node_modules\yaml-language-server\out\server\src\server.js:338:37)
    at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (c:\Users\semidefinite\.vscode\extensions\redhat.vscode-yaml-0.0.13\node_modules\yaml-language-server\out\server\src\server.js:327:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 8:46:15 PM] Connection to server got closed. Server will restart.
```
Inspection of js-yaml\lib\js-yaml\type.js reveals the following [definition](https://github.com/nodeca/js-yaml/blob/2d1fbed8f3a76ff93cccb9a8a418b4c4a482d3d9/lib/js-yaml/type.js#L16-L20):

	var YAML_NODE_KINDS = [
	  'scalar',
	  'sequence',
	  'mapping'
	];

If I replace "!Ref Scalar" with "!Ref scalar" all is well.

**Comment by JPinkney** [comment]
Added
