### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by dstadelm** [redhat-developer/yaml-language-server#893]
When starting the language server standalone or from within neovim I get following error 
```bash
/home/user/node_modules/yaml-language-server/out/server/src/languageservice/services/yamlSchemaService.js:542
                unresolvedJsonSchema.schema.title = name ?? unresolvedJsonSchema.schema.title;
                                                          ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/node_modules/yaml-language-server/out/server/src/languageservice/yamlLanguageService.js:9:29)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

It used to work. I haven't changed the setup. Anything I could be missing?

**Comment by dstadelm** [comment]
Playing around I've found out that the issue is resolved when installing manually instead of npm

**Comment by dstadelm** [comment]
It seems, that the Node.js version installed with Ubuntu 22.04 is to old (12.2.2) using a PPA providing a newer Node version resolved the problem completely.
