### ISSUE TITLE
yaml file input prompt:Channel has been closed

### ISSUE THREAD

**Issue by anlem12** [redhat-developer/yaml-language-server#95]
yaml file input prompt:Channel has been closed

`
版本: 1.27.2 (user setup)

提交: f46c4c469d6e6d8c46f268d1553c5dc4b475840f

日期: 2018-09-12T16:17:45.060Z

Electron: 2.0.7

Chrome: 61.0.3163.100

Node.js: 8.9.3

V8: 6.1.534.41

架构: x64
`

`[2018-09-28 08:30:39.347] [exthost1] [info] ExtensionService#loadCommonJSModule C:\Users\xxx\.vscode\extensions\dbaeumer.vscode-eslint-1.6.0\client\out\extension

[2018-09-28 08:30:39.402] [exthost1] [info] ExtensionService#_doActivateExtension redhat.vscode-yaml {"startup":false,"activationEvent":"onLanguage:yaml"}

[2018-09-28 08:30:39.402] [exthost1] [info] ExtensionService#loadCommonJSModule C:\Users\xxx\.vscode\extensions\redhat.vscode-yaml-0.0.16\out\src\extension
[2018-09-28 08:30:40.329] [exthost1] [info] eager extensions activated`

**Comment by JPinkney** [comment]
What exactly is happening? is the language server erroring on start? Do you mind making a video showing the error

**Comment by anlem12** [comment]
`c:\Users\xxx\.vscode\extensions\redhat.vscode-yaml-0.0.16\node_modules\yaml-language-server\out\server\src\languageservice\parser\yamlParser.js:197

        const typeInfo = tag.split(' ');
                             ^


TypeError: tag.split is not a function

    at js_yaml_1.Schema.create.customTags.map (c:\Users\xxx\.vscode\extensions\redhat.vscode-yaml-0.0.16\node_modules\yaml-language-server\out\server\src\languageservice\parser\yamlParser.js:197:30)

    at Array.map (<anonymous>)

    at Object.parse (c:\Users\xxx\.vscode\extensions\redhat.vscode-yaml-0.0.16\node_modules\yaml-language-server\out\server\src\languageservice\parser\yamlParser.js:196:71)

    at validateTextDocument (c:\Users\xxx\.vscode\extensions\redhat.vscode-yaml-0.0.16\node_modules\yaml-language-server\out\server\src\server.js:338:37)

    at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (c:\Users\xxx\.vscode\extensions\redhat.vscode-yaml-0.0.16\node_modules\yaml-language-server\out\server\src\server.js:327:9)

    at ontimeout (timers.js:475:11)

    at tryOnTimeout (timers.js:310:5)

    at Timer.listOnTimeout (timers.js:270:5)

[Info  - 9:00:38 AM] Connection to server got closed. Server will restart.`

**Comment by JPinkney** [comment]
I've taken a look at custom tags again and this should be fixed with version 0.3.0.
